name: Simple go build
run-name: Pipeline run by @${{ github.actor }}

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
    workflow_dispatch:
        inputs:
            title:
                description: 'Title name'
                type: string

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: print title
              run: echo ${{ inputs.title }}
            - name: Setup Go version
              uses: actions/setup-go@v4
              with:
                go-version: '1.21.4'
            - name: execute
              run : go run helloworld.go