name: Simple go build

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Setup Go version
              uses: actions/setup-go@v4
              with:
                go-version: '1.21.4'
            - run : go run helloworld.go